#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define BLACK_LINE 35

typedef enum {FORWARD, STOP, BACKWARDS, TURN_LEFT, TURN_RIGHT, FORWARD_LEFT, FORWARD_RIGHT} direction_type;
direction_type direction;

void power(direction_type value, int percentage){
	int left, right, rotation = -1;
	switch(value){
		case FORWARD:
			left = 100;
			right = 100;
			break;
		case STOP:
			left = 0;
			right = 0;
			break;
		case BACKWARDS:
			left = -100;
			right = -100;
			break;
		case TURN_LEFT:
			left = -100;
			right = 100;
			break;
		case TURN_RIGHT:
			left = 100;
			right = -100;
			break;
		case FORWARD_LEFT:
			left = 25;
			right = 100;
			break;
		case FORWARD_RIGHT:
			left = 100;
			right = 25;
			break;
	}
	motor[motorB] = right * (percentage/100) * rotation;
	motor[motorC] = left * (percentage/100) * rotation;
}

int detectEnemy(){
	direction = TURN_RIGHT;
	power(direction, 100);
	while(!(SensorValue[sonar] < 100 && SensorValue[sonar] > 0)){}
	direction = STOP;
	power(direction, 100);
	return 1;
}

int detectRing(){
	if(SensorValue[light] < BLACK_LINE){
		direction =STOP;
		power(direction, 100);
	}
	return 1;
}

task main()
{
	while(true){
		while(detectEnemy()){
			direction = FORWARD;
			power(direction, 100);
		}
		if(detectRing()){
			direction = STOP;
			power(direction, 100);
		}
	}
}
