#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
#pragma config(Sensor, S2,     sonarSensor,    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define turnTime 550
#define somethingClose 40
#define highSpeed -80
#define noSpeed 0
#define reverseSpeed 80

void turnLeft()
{
	motor[motorC] = noSpeed;
	motor[motorB] = reverseSpeed;
	wait1Msec(turnTime);
	motor[motorB] = noSpeed;
}

void turnRight()
{
	motor[motorB] = noSpeed;
	motor[motorC] = reverseSpeed;
	wait1Msec(turnTime);
	motor[motorC] = noSpeed;
}

task main()
{
	// wait 50 msec to initialize light sensor
	wait1Msec(50);

	int dir = 0;

	while(true)
	{
		// run ahead to slam against something
		motor[motorB] = highSpeed;
		motor[motorC] = highSpeed;
		while(SensorValue[touchSensor] == 0){};

		// Stop
		motor[motorB] = noSpeed;
		motor[motorC] = noSpeed;
		wait1Msec(100);

		// turn
		turnRight();
		motor[motorB] = highSpeed;
		motor[motorC] = highSpeed;
		while(SensorValue[sonarSensor] < somethingClose && SensorValue[touchSensor] == 0){};
		wait1Msec(100);
		motor[motorB] = noSpeed;
		motor[motorC] = noSpeed;
		wait1Msec(100);
		dir = (SensorValue[touchSensor] == 1) ? -1 : 1;
		if(dir == -1) {
			motor[motorB] = highSpeed * dir;
			motor[motorC] = highSpeed * dir;
			while(SensorValue[sonarSensor] < somethingClose){};
			wait1Msec(100);

			// Stop
			motor[motorB] = noSpeed;
			motor[motorC] = noSpeed;
			wait1Msec(100);
		}
		turnLeft();
		motor[motorB] = highSpeed;
		motor[motorC] = highSpeed;
		wait1Msec(250);

		// Stop
		motor[motorB] = noSpeed;
		motor[motorC] = noSpeed;
		wait1Msec(100);

	}
}
